FROM jenkins/jenkins:lts-jdk17

LABEL maintainer="Sample_Docker"

USER root

RUN brew update && brew install -y maven

USER jenkins

ENV MAVEN_HOME /usr/share/maven

ENV PATH $MAVEN_HOME/bin:$PATH

EXPOSE 8081